name: ci

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci --prefer-offline --no-audit
      - run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci --prefer-offline --no-audit
      - run: npm run test

  publish-npm:
    if: github.event_name == 'push' && github.repository == 'Basssiiie/OpenRCT2-FlexUI'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: npm ci --prefer-offline --no-audit
      - run: npm run build
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
